### ISSUE TITLE
react-vr-cli can't init project -- strict mode

### ISSUE THREAD

**Issue by infoxiao** [facebook/react-vr#81]
### Description

I updated the react-vr-cli to 0.2.1 but cannot seem to init projects.
I have no problem with react-vr-cli 0.1.5

#### Expected behavior
When I ran ``react-vr init WelcomeToVr``, a SyntaxError was reported

#### Actual behavior

See log below

#### Logs
```
/opt/local/lib/node_modules/react-vr-cli/src/listGenerators.js:27
    for (let i = 0; i < info.length; i++) {
         ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/local/lib/node_modules/react-vr-cli/src/generateFiles.js:11:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

### Additional Information

* Operating System: [MacOS]
* Browser: [Chrome]

**Comment by andrewimm** [comment]
Sorry about that, update to 0.2.2 and the issue should be fixed.

**Comment by infoxiao** [comment]
Cool fixed. Thanks.
